server:
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /quick_blog
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps : true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    mvc:
      throw-exception-if-no-handler-found: true

      static-path-pattern: /static/**
    resources:
      add-mappings: false

#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.weng.quick_blog.entity.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty

  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false